---
deployment:
  tasks:
    - export DEPLOYPATH=/home/camptell/webapp
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env.example 2>/dev/null || true
    - cd $DEPLOYPATH
    - /opt/cpanel/ea-php83/root/usr/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/bin/npm install
    - /usr/bin/npm run build
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan config:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan route:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan view:cache
    - rm -rf /home/camptell/public_html/*
    - /bin/cp -rL $DEPLOYPATH/public/* /home/camptell/public_html/
    - /bin/cp $DEPLOYPATH/public/.htaccess /home/camptell/public_html/.htaccess
    - chmod -R 755 /home/camptell/public_html
